flask_app/main/routes.py
from flask import render_template, request, current_app, Blueprint, redirect, url_for
from flask_app.giphyUtils import getRandomGIF
import json
from flask_app.models import GIFPost

main = Blueprint("main", __name__)

@main.route("/")
@main.route("/index")
def index():
    GIFs = GIFPost.query.all()[::-1]
    return render_template("index.html", title="All GIF Posts", posts=GIFs)

@main.route("/description")
def description():
    return render_template("description.html", title="Description of App")

@main.route("/random")
def random():
    url = getRandomGIF()
    return render_template("random.html", title="Random GIF", url=url)


@main.route("/csp_error_handling", methods=["POST"])
def report_handler():
    """
    Receives POST requests from the browser whenever the Content-Security-Policy 
    is violated. Processes the data and logs an easy-to-read version of the message
    in your console.
    """
    report = json.loads(request.data.decode())["csp-report"]

    # current_app.logger.info(json.dumps(report, indent=2))

    violation_desc = (
        "\nViolated directive: %s, \nBlocked: %s, \nOriginal policy: %s \n"
        % (
            report["violated-directive"],
            report["blocked-uri"],
            report["original-policy"],
        )
    )

    current_app.logger.info(violation_desc)
    return redirect(url_for("main.index"))

flask_app/posts/routes.py
from flask import render_template, request, current_app, Blueprint, redirect, url_for

from flask_app import db
from flask_app.models import GIFPost
from flask_app.posts.forms import CreatePostForm

posts = Blueprint("posts", __name__)
main = Blueprint("main", __name__)

@posts.route("/create_post", methods=["GET", "POST"])
def create_post():
    form = CreatePostForm()

    if form.validate_on_submit():
        gifPost = GIFPost(
            title = form.title.data,
            link = form.link.data
        )

        db.session.add(gifPost)
        db.session.commit()

        return redirect(url_for("main.index"))

    return render_template(
        "createGIFPost.html", title="Create GIF POST!", form=form
    )

flask_app/users/routes.py
from flask import render_template, current_app, url_for, redirect, request, Blueprint, session
from flask_login import login_user, current_user, logout_user, login_required

from flask_app import db, bcrypt
from flask_app.models import User, UserGIF
from flask_app.users.forms import RegistrationForm, LoginForm, UpdateInterestsForm
from flask_app.giphyUtils import getGIFs
from datetime import datetime

import qrcode
import qrcode.image.svg as svg

from io import BytesIO

users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        current_app.logger.info("User is authenticated. Redirect to main page.")
        return redirect(url_for("main.index"))

    form = RegistrationForm()

    if form.validate_on_submit():
        current_app.logger.info("POST Request hit at /register and form has been validated")
        current_app.logger.info("Hashing password...")

        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")

        current_app.logger.info("Creating new user")

        user = User(
            username=form.username.data, 
            password=hashed, 
            interest1=form.firstInterest.data, 
            interest2=form.secondInterest.data,
            interest3=form.thirdInterest.data
            )

        current_app.logger.info("Adding new user to database")
        db.session.add(user)
        db.session.commit()

        current_app.logger.info("Getting GIFS for User {user.username}")
        firstInterestGIFs = getGIFs(user.interest1)
        for url in firstInterestGIFs:
            userGIF = UserGIF(link = url, user = user)
            db.session.add(userGIF)
        

        secondInterestGIFs = getGIFs(user.interest2)
        for url in secondInterestGIFs:
            userGIF = UserGIF(link = url, user = user)
            db.session.add(userGIF)

        thirdInterestGIFs = getGIFs(user.interest3)
        for url in thirdInterestGIFs:
            userGIF = UserGIF(link = url, user = user)
            db.session.add(userGIF)
        db.session.commit()

        current_app.logger.info("User has been added, as well as their GIF Interests. Redirect to login page.")

        #return redirect(url_for("users.login"))
        session['reg_username'] = user.username

        return redirect(url_for('users.tfa'))

    return render_template("register.html", title="Register", form=form)

@users.route("/tfa")
def tfa():
    if 'reg_username' not in session:
        return redirect(url_for('main.index'))

    headers = {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return render_template('tfa.html'), headers

@users.route("/qr_code")
def qr_code():
    if 'reg_username' not in session:
        return redirect(url_for('main.index'))
    
    user = User.query.filter_by(username=session['reg_username']).first()

    session.pop('reg_username')

    img = qrcode.make(user.get_auth_uri(), image_factory=svg.SvgPathImage)

    stream = BytesIO()

    img.save(stream)

    headers = {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return stream.getvalue(), headers

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        current_app.logger.info("User is authenticated. Redirect to main page.")

        return redirect(url_for("main.index"))

    form = LoginForm()

    if form.validate_on_submit():
        current_app.logger.info("POST Request hit at /login and form has been validated")
        current_app.logger.info("Checking password...")

        user = User.query.filter_by(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            current_app.logger.info("Logging in user...")
            login_user(user)

            current_app.logger.info("User logged in")

            return redirect(url_for("users.account"))

    return render_template("login.html", title="Login", form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))

@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateInterestsForm()

    if form.validate_on_submit():
        current_app.logger.info("POST Request hit at /account and form has been validated")
        current_app.logger.info("Updating Interests...")

        current_user.interest1 = form.firstInterest.data
        current_user.interest2 = form.secondInterest.data
        current_user.interest3 = form.thirdInterest.data
        current_user.lastUpdated = datetime.utcnow()
        updateUserGIFs()

        return redirect(url_for("users.account"))

    elif request.method == "GET":
        current_app.logger.info("GET Request hit at /account")
        form.firstInterest.data = current_user.interest1
        form.secondInterest.data = current_user.interest2
        form.thirdInterest.data = current_user.interest3

    timeDifference = datetime.utcnow() - current_user.lastUpdated
    hoursSinceUpdate = divmod(timeDifference.total_seconds(), 3600)[0]
    
    return render_template("account.html", title="Account", form=form, hoursSinceUpdate=hoursSinceUpdate)

@users.route("/userFeed")
@login_required
def userFeed():
    current_app.logger.info("GET Request hit at /userFeed")
    lastUpdatedTime = current_user.lastUpdated
    timeDifference = datetime.utcnow() - lastUpdatedTime
            
    hoursSinceUpdate = divmod(timeDifference.total_seconds(), 3600)[0]
    current_app.logger.info(f"User profile last updated {hoursSinceUpdate} hours ago")

    # minutesSinceUpdate = divmod(timeDifference.total_seconds(), 60)[0]
    # current_app.logger.info(f"User profile last updated {minutesSinceUpdate} minutes ago")

    if hoursSinceUpdate >= 24:
        current_app.logger.info(f"User profile last updated at least 24 hours ago, so update their GIFs")
        updateUserGIFs()
    
    userGIFs = UserGIF.query.filter_by(user = current_user).all()
    userGIFs = map(lambda x : x.link, userGIFs)
    return render_template("userFeed.html", title = "Daily GIFs Feed", userGIFs = userGIFs)
        

def updateUserGIFs():
    firstInterestGIFs = getGIFs(current_user.interest1)
    secondInterestGIFs = getGIFs(current_user.interest2)
    thirdInterestGIFs = getGIFs(current_user.interest3)
    gifs = firstInterestGIFs + secondInterestGIFs + thirdInterestGIFs

    i = 0
    userGIFs = UserGIF.query.filter_by(user = current_user).all()
    for c in userGIFs:
        c.link = gifs[i]
        i += 1

    current_user.lastUpdated = datetime.utcnow()
    db.session.commit()
    

    

flask_app/templates/account.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>{{ current_user.username }}</h2>
    <p>Profile Last Updated: {{hoursSinceUpdate}} hours ago</p>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.firstInterest.label(class="form-control-label") }}
            {{ form.firstInterest(class="form-control form-control-lg") }}
            {% if form.firstInterest.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.firstInterest.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.secondInterest.label(class="form-control-label") }}
            {{ form.secondInterest(class="form-control form-control-lg") }}
            {% if form.secondInterest.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.secondInterest.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.thirdInterest.label(class="form-control-label") }}
            {{ form.thirdInterest(class="form-control form-control-lg") }}
            {% if form.thirdInterest.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.thirdInterest.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.submit(class="form-control form-control-lg") }}
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href={{ url_for('static', filename='css/custom.css') }}>

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Flask App</title>
    {% endif %}
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">

            <a class="navbar-brand" href={{ url_for('main.index' )}}>Today is a GIF</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarToggle">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href={{ url_for('main.index') }} class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('main.description') }} class="nav-link">Description of App</a>
                    </li>
                    <li class="nav-item">
                            <a href={{ url_for('main.random') }} class="nav-link">Random GIF</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('posts.create_post') }} class="nav-link">Create GIF Post!</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.userFeed') }} class="nav-link">Daily GIFs Feed</a>
                    </li>
                </ul>

                {% if current_user.is_authenticated %}
                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href=# class="nav-link">Logged in as: <b>{{ current_user.username }}</b></a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.account' )}} class="nav-link">My Account</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.logout' )}} class="nav-link">Logout</a>
                    </li>
                </ul>

                {% else %}

                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href={{ url_for('users.login' )}} class="nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.register' )}} class="nav-link">Register</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}{% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

flask_app/templates/createGIFPost.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>Post a link to a GIF!</h2>
    <p>Make sure that the link has a .gif extension! :)</p>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.title.label(class="form-control-label") }}
            {{ form.title(class="form-control form-control-md") }}

            {% if form.title.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ form.link.label(class="form-control-label") }}
            {{ form.link(class="form-control form-control-md", rows=10) }}

            {% if form.link.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.link.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            {{ form.submit(class="form-control form-control-lg") }}

        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/description.html
{% extends "base.html" %}
{% block content %}

<h1>{{title}}</h1>

<p>Created by Shad Khan, this is a GIF sharing/feed web application. 
    All users will have the ability to upload and share GIFs to a main feed. 
    Logged in users have the ability to create and set GIF preferences and access to their own feed page.
    This personalized feed page retrieves daily tailored GIFs based on a logged-in user's interests via the Giphy Client Python package
    (wrapper to the Giphy API). Users also have the ability to update their interests whenever they want, resulting in a new set of tailored GIFs. 
</p>
{% endblock %}

flask_app/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>{{title}}</h1>

<div class="GIFGallery">
    {% for post in posts %}
    <a class="GIFlink">
        <figure>
            <img src={{ post.link }} alt="">
            <figcaption> {{post.title}} </figcaption>
        </figure>
    </a>
    {% endfor %}
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>{{title}}</h2>
</div>
<div>
    If you <b>don't</b> have an account, then <a href={{ url_for('users.register') }}>Register!</a>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.username.label(class="form-control-label green-text") }}
            {{ form.username(class="form-control form-control-md") }}

            {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control form-control-lg") }}
        </div>

        <div>
            {{ form.token.label(class="form-control-label green-text") }}
            {{ form.token(class="form-control form-control-md") }}

            {% if form.token.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.token.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <div>
            {{ form.submit(class="form-control form-control-lg") }}
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/random.html
{% extends "base.html" %}
{% block content %}
<h1>{{title}}</h1>
<img id="random" src={{ url }} alt="">

{% endblock %}

flask_app/templates/register.html
{% extends "base.html" %}
{% block content %}
<div>
    <h2>{{title}}</h2>
</div>
<div>
    If you already have an account, then just <a href={{ url_for('users.login') }}>Log In!</a>
</div>
<!-- Registration Form: -->
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.username.label(class="form-control-label") }}
            {{ form.username(class="form-control form-control-lg") }}
            {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
         </div>
        <div>
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control form-control-lg") }}
            {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.confirm_password.label(class="form-control-label") }}
            {{ form.confirm_password(class="form-control form-control-lg") }}
            {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.firstInterest.label(class="form-control-label") }}
            {{ form.firstInterest(class="form-control form-control-lg") }}
            {% if form.firstInterest.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.firstInterest.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.secondInterest.label(class="form-control-label") }}
            {{ form.secondInterest(class="form-control form-control-lg") }}
            {% if form.secondInterest.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.secondInterest.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.thirdInterest.label(class="form-control-label") }}
            {{ form.thirdInterest(class="form-control form-control-lg") }}
            {% if form.thirdInterest.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.thirdInterest.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.submit(class="form-control form-control-lg") }}
        </div>
    </form>
</div>

{% endblock %}

flask_app/templates/tfa.html
{% extends "base.html" %}
{% block content %}
    <div>
        <h1>Two-Factor Auth Enrollment</h1>
    </div>
    <div>
        This website requires mandatory 2FA enrollment. 
    </div>
    <!-- Registration Form: -->
    <p>
        Use a authenticator app (such as DuoMobile) to enroll with us! You will need to use this app to login in the future. 
        Once you've downloaded the app, just use your phone camera and scan the barcode! This will open the authenticator app, which will have a constantly updating
        authentication 6 digit code that you will use to login!
    </p>
    <img src={{ url_for('users.qr_code') }} alt="QR Code for 2FA">

    <div>
        When you're done, you can go to the <a href={{ url_for('users.login') }}>Login page</a>!
    </div>
{% endblock %}

flask_app/templates/userFeed.html
{% extends "base.html" %}
{% block content %}
<h1>{{title}}</h1>

<div class="GIFGallery">
    {% for link in userGIFs %}
    <a class="GIFlink">
        <figure>
            <img src={{ link }} alt="">
        </figure>
    </a>
    {% endfor %}
</div>
{% endblock %}